#!/bin/bash

if ! command -v cliamp >/dev/null 2>&1; then
    skipped "cliamp"
fi

theme_template="$HOME/.config/omarchy/current/theme/cliamp.toml"
theme_dir="$HOME/.config/cliamp/themes"
mkdir -p "$theme_dir"

if [ ! -f "$theme_template" ]; then
    cat > "$theme_template" << EOF
# Omarchy theme for cliamp
# Generated by Omarchy theme hook — do not edit manually.

accent    = "#${normal_blue}"
bright_fg = "#${bright_white}"
fg        = "#${normal_white}"
green     = "#${normal_green}"
yellow    = "#${normal_yellow}"
red       = "#${normal_red}"
EOF
fi

cp -f "$theme_template" "$theme_dir/omarchy.toml"

config_file="$HOME/.config/cliamp/config.toml"
if [ -f "$config_file" ] && ! grep -q 'theme = "omarchy"' "$config_file"; then
    sed -i 's/^theme = ".*"/theme = "omarchy"/' "$config_file"
fi

success "cliamp theme updated!"
exit 0
